### ISSUE TITLE
ClassCastException 

### ISSUE THREAD

**Issue by Narimm** [GamerKing195/AutoUpdaterAPI#2]
I am using a similar method as you to auto update a premium resource..

https://github.com/GamerKing195/AutoUpdaterAPI/blob/2202bf7e4f23923be5b4048e33f036a25d6a4e78/src/main/java/com/gamerking195/dev/autoupdaterapi/PremiumUpdater.java#L177

java.lang.ClassCastException: com.gargoylesoftware.htmlunit.UnexpectedPage cannot be cast to com.gargoylesoftware.htmlunit.html.HtmlPage

I am getting this exception when hitting a premium resource I have purchased...any ideas?

**Comment by cadenkriese** [comment]
This error would happen whenever a resource doesn't exist likely seeing as it is returning an unexpected page, apologies for the bad error logging on this one, the API I use for navigating spigot isn't very good at passing down exceptions.

**Comment by Narimm** [comment]
I ended up not casting to the HTML page - the interface is good enough to return the page anyway

**Comment by cadenkriese** [comment]
Ok, glad you resolved this.
