### ISSUE TITLE
PLUGIN NOT LOADING

### ISSUE THREAD

**Issue by SladeHazard** [GamerKing195/AutoUpdaterAPI#7]
Server Version 1.12.2 Paper
Plugins i'm using Up2date,AutoUpdaterAPI and I'm also using mvdwplaceholderapi if that's important for some reason AutoUpdaterAPI is not loading tried deleting mvdwplugin folder
Error Log: https://paste.helpch.at/xojuzoboye.md

**Comment by cadenkriese** [comment]
Hi there, I'm not supporting AutoUpdaterAPI or Up2Date as of now.
I'm working on a rewrite of both of those projects, and once they are complete, I will begin providing support again.

Apologies for any inconvenience I have caused,
    - flogic
